import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:lucide_icons/lucide_icons.dart';
import '../../../../config/theme.dart';
import '../../../../core/api/api_client.dart';
import '../../../../shared/widgets/app_loader.dart';

final aiAnalyticsProvider = FutureProvider<Map<String, dynamic>>((ref) async {
  final apiClient = ref.read(apiClientProvider);
  final response = await apiClient.getAiAdminAnalytics();
  return response.data['data'] as Map<String, dynamic>;
});

class AdminAiAnalyticsScreen extends ConsumerWidget {
  const AdminAiAnalyticsScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final aiAnalyticsAsync = ref.watch(aiAnalyticsProvider);

    return Scaffold(
      backgroundColor: AppTheme.offWhite,
      appBar: AppBar(
        title: const Text('Setu AI Insights', style: TextStyle(fontWeight: FontWeight.bold)),
        actions: [
          IconButton(
            icon: const Icon(Icons.refresh_rounded),
            onPressed: () => ref.invalidate(aiAnalyticsProvider),
          ),
        ],
      ),
      body: aiAnalyticsAsync.when(
        loading: () => const Center(child: AppLoader()),
        error: (e, _) => Center(child: Text('Failed to load AI insights: $e')),
        data: (data) => _buildContent(context, data),
      ),
    );
  }

  Widget _buildContent(BuildContext context, Map<String, dynamic> data) {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(20),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header Badge
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 6),
            decoration: BoxDecoration(
              color: AppTheme.primaryRed.withValues(alpha: 0.1),
              borderRadius: BorderRadius.circular(20),
            ),
            child: const Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                Icon(Icons.auto_awesome_rounded, size: 14, color: AppTheme.primaryRed),
                SizedBox(width: 6),
                Text(
                  'GENERATED BY SETU AI 2.0',
                  style: TextStyle(
                    fontSize: 10,
                    fontWeight: FontWeight.w900,
                    letterSpacing: 1,
                    color: AppTheme.primaryRed,
                  ),
                ),
              ],
            ),
          ).animate().fadeIn().slideX(begin: -0.2),

          const SizedBox(height: 24),

          // Executive Summary Card
          _buildInsightCard(
            title: 'Executive Summary',
            content: data['executiveSummary'] ?? 'No summary available.',
            icon: LucideIcons.fileText,
            color: Colors.blue,
          ).animate().fadeIn(delay: 100.ms).slideY(begin: 0.1),

          const SizedBox(height: 16),

          // Key Trend
          _buildInsightCard(
            title: 'Key Trend',
            content: data['keyTrend'] ?? 'No trend detected.',
            icon: LucideIcons.trendingUp,
            color: Colors.orange,
          ).animate().fadeIn(delay: 200.ms).slideY(begin: 0.1),

          const SizedBox(height: 16),

          // Recommendation
          _buildInsightCard(
            title: 'Action Recommendation',
            content: data['recommendation'] ?? 'No recommendation available.',
            icon: LucideIcons.lightbulb,
            color: Colors.green,
          ).animate().fadeIn(delay: 300.ms).slideY(begin: 0.1),

          const SizedBox(height: 16),

          // Predicted Needs
          _buildInsightCard(
            title: 'Predicted High Demand',
            content: 'Setu AI predicts a spike in demand for: ${data['predictedNeeds'] ?? 'Unknown'}',
            icon: LucideIcons.calendar,
            color: Colors.purple,
          ).animate().fadeIn(delay: 400.ms).slideY(begin: 0.1),
          
          const SizedBox(height: 40),
          
          Center(
            child: Text(
              'Last updated: ${DateTime.now().toString().split('.')[0]}',
              style: const TextStyle(fontSize: 11, color: AppTheme.gray),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildInsightCard({
    required String title,
    required String content,
    required IconData icon,
    required Color color,
  }) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(24),
        boxShadow: [
          BoxShadow(
            color: color.withValues(alpha: 0.1),
            blurRadius: 20,
            offset: const Offset(0, 10),
          ),
        ],
        border: Border.all(color: color.withValues(alpha: 0.1), width: 1.5),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                padding: const EdgeInsets.all(10),
                decoration: BoxDecoration(
                  color: color.withValues(alpha: 0.1),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Icon(icon, size: 20, color: color),
              ),
              const SizedBox(width: 14),
              Text(
                title.toUpperCase(),
                style: TextStyle(
                  fontSize: 12,
                  fontWeight: FontWeight.w900,
                  letterSpacing: 1,
                  color: color.withValues(alpha: 0.8),
                ),
              ),
            ],
          ),
          const SizedBox(height: 16),
          Text(
            content,
            style: const TextStyle(
              fontSize: 15,
              height: 1.5,
              color: AppTheme.charcoal,
              fontWeight: FontWeight.w500,
            ),
          ),
        ],
      ),
    );
  }
}
